import 'dotenv/config';
import { PrismaClient } from '@prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';
import { Pool } from 'pg';

const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

const foods = [
  // ─── PROTEINS & MEATS ──────────────────────────────────────────────────────
  {
    name: 'Chicken Breast (Cooked, Boneless/Skinless)',
    brand: 'Generic / USDA',
    servingSize: '100g',
    calories: 165,
    protein: 31.0,
    carbs: 0.0,
    fat: 3.6,
    barcode: '8410000000001',
    verified: true,
  },
  {
    name: 'Chicken Thigh (Cooked, Boneless/Skinless)',
    brand: 'Generic / USDA',
    servingSize: '100g',
    calories: 209,
    protein: 26.0,
    carbs: 0.0,
    fat: 10.9,
    barcode: '8410000000002',
    verified: true,
  },
  {
    name: 'Beef Sirloin Steak (Lean, Cooked)',
    brand: 'Generic / USDA',
    servingSize: '100g',
    calories: 250,
    protein: 26.5,
    carbs: 0.0,
    fat: 15.0,
    barcode: '8410000000003',
    verified: true,
  },
  {
    name: 'Ground Beef 90/10 (Cooked)',
    brand: 'Generic / USDA',
    servingSize: '100g',
    calories: 214,
    protein: 26.7,
    carbs: 0.0,
    fat: 11.0,
    barcode: '8410000000004',
    verified: true,
  },
  {
    name: 'Atlantic Salmon (Cooked)',
    brand: 'Generic / USDA',
    servingSize: '100g',
    calories: 206,
    protein: 22.1,
    carbs: 0.0,
    fat: 12.3,
    barcode: '8410000000005',
    verified: true,
  },
  {
    name: 'White Fish fillet (Tilapia/Cod, Cooked)',
    brand: 'Generic / USDA',
    servingSize: '100g',
    calories: 105,
    protein: 23.0,
    carbs: 0.0,
    fat: 0.9,
    barcode: '8410000000006',
    verified: true,
  },
  {
    name: 'Whole Egg (Large, Boiled/Poached)',
    brand: 'Generic / USDA',
    servingSize: '1 large (50g)',
    calories: 78,
    protein: 6.3,
    carbs: 0.6,
    fat: 5.3,
    barcode: '8410000000007',
    verified: true,
  },
  {
    name: 'Egg White (Raw/Cooked)',
    brand: 'Generic / USDA',
    servingSize: '100g (approx 3 whites)',
    calories: 52,
    protein: 10.9,
    carbs: 0.7,
    fat: 0.2,
    barcode: '8410000000008',
    verified: true,
  },
  {
    name: 'Tofu (Firm, Calcium-set)',
    brand: 'Generic',
    servingSize: '100g',
    calories: 144,
    protein: 17.3,
    carbs: 2.8,
    fat: 8.7,
    barcode: '8410000000009',
    verified: true,
  },
  {
    name: 'Shrimp (Cooked)',
    brand: 'Generic / USDA',
    servingSize: '100g',
    calories: 99,
    protein: 24.0,
    carbs: 0.2,
    fat: 0.3,
    barcode: '8410000000010',
    verified: true,
  },

  // ─── CARBS & GRAINS ────────────────────────────────────────────────────────
  {
    name: 'White Rice (Cooked, Jasmine/Long-grain)',
    brand: 'Generic',
    servingSize: '100g (1/2 cup cooked)',
    calories: 130,
    protein: 2.7,
    carbs: 28.2,
    fat: 0.3,
    barcode: '8410000000011',
    verified: true,
  },
  {
    name: 'Brown Rice (Cooked)',
    brand: 'Generic',
    servingSize: '100g',
    calories: 112,
    protein: 2.3,
    carbs: 23.5,
    fat: 0.8,
    barcode: '8410000000012',
    verified: true,
  },
  {
    name: 'Rolled Oats (Dry/Uncooked)',
    brand: 'Generic / Quaker',
    servingSize: '50g (1/2 cup dry)',
    calories: 189,
    protein: 6.8,
    carbs: 33.8,
    fat: 3.5,
    barcode: '8410000000013',
    verified: true,
  },
  {
    name: 'Sweet Potato (Baked/Boiled with skin)',
    brand: 'Generic / USDA',
    servingSize: '100g',
    calories: 90,
    protein: 2.0,
    carbs: 20.7,
    fat: 0.1,
    barcode: '8410000000014',
    verified: true,
  },
  {
    name: 'Potato (Russet/White, Baked)',
    brand: 'Generic / USDA',
    servingSize: '100g',
    calories: 93,
    protein: 2.5,
    carbs: 21.1,
    fat: 0.1,
    barcode: '8410000000015',
    verified: true,
  },
  {
    name: 'Whole Wheat Bread',
    brand: 'Generic Bakery',
    servingSize: '1 slice (35g)',
    calories: 82,
    protein: 4.0,
    carbs: 13.8,
    fat: 1.1,
    barcode: '8410000000016',
    verified: true,
  },
  {
    name: 'Sourdough Bread',
    brand: 'Generic Bakery',
    servingSize: '1 slice (50g)',
    calories: 130,
    protein: 4.8,
    carbs: 25.5,
    fat: 0.8,
    barcode: '8410000000017',
    verified: true,
  },
  {
    name: 'Pasta / Spaghetti (Cooked)',
    brand: 'Generic / Barilla',
    servingSize: '100g cooked',
    calories: 158,
    protein: 5.8,
    carbs: 30.9,
    fat: 0.9,
    barcode: '8410000000018',
    verified: true,
  },
  {
    name: 'Quinoa (Cooked)',
    brand: 'Generic',
    servingSize: '100g cooked',
    calories: 120,
    protein: 4.4,
    carbs: 21.3,
    fat: 1.9,
    barcode: '8410000000019',
    verified: true,
  },
  {
    name: 'Rice Noodles (Pho Noodles, Cooked)',
    brand: 'Generic',
    servingSize: '100g cooked',
    calories: 109,
    protein: 0.9,
    carbs: 25.2,
    fat: 0.2,
    barcode: '8410000000020',
    verified: true,
  },

  // ─── DAIRY & SUPPLEMENTS ───────────────────────────────────────────────────
  {
    name: 'Whey Protein Isolate Powder',
    brand: 'Optimum Nutrition Gold Standard',
    servingSize: '1 scoop (31g)',
    calories: 120,
    protein: 24.0,
    carbs: 3.0,
    fat: 1.5,
    barcode: '748927028448',
    verified: true,
  },
  {
    name: 'Clear Whey Isolate',
    brand: 'MyProtein',
    servingSize: '1 scoop (25g)',
    calories: 85,
    protein: 20.0,
    carbs: 0.6,
    fat: 0.1,
    barcode: '5055960812345',
    verified: true,
  },
  {
    name: 'Greek Yogurt (0% Fat, Plain)',
    brand: 'Chobani / Fage',
    servingSize: '100g',
    calories: 59,
    protein: 10.3,
    carbs: 3.6,
    fat: 0.4,
    barcode: '8410000000021',
    verified: true,
  },
  {
    name: 'Cottage Cheese (Low Fat 2%)',
    brand: 'Generic',
    servingSize: '100g',
    calories: 84,
    protein: 11.0,
    carbs: 4.3,
    fat: 2.3,
    barcode: '8410000000022',
    verified: true,
  },
  {
    name: 'Whole Milk (3.25% Fat)',
    brand: 'Generic Dairy',
    servingSize: '1 cup (240ml)',
    calories: 149,
    protein: 7.7,
    carbs: 11.7,
    fat: 7.9,
    barcode: '8410000000023',
    verified: true,
  },
  {
    name: 'Almond Milk (Unsweetened)',
    brand: 'Almond Breeze',
    servingSize: '1 cup (240ml)',
    calories: 30,
    protein: 1.0,
    carbs: 1.0,
    fat: 2.5,
    barcode: '041570054171',
    verified: true,
  },
  {
    name: 'Protein Bar (Chocolate Peanut Butter)',
    brand: 'Quest Nutrition',
    servingSize: '1 bar (60g)',
    calories: 200,
    protein: 20.0,
    carbs: 21.0,
    fat: 8.0,
    barcode: '886280001007',
    verified: true,
  },
  {
    name: 'Creatine Monohydrate (Unflavored)',
    brand: 'KavrioLab Pure',
    servingSize: '1 scoop (5g)',
    calories: 0,
    protein: 0.0,
    carbs: 0.0,
    fat: 0.0,
    barcode: '8410000000024',
    verified: true,
  },

  // ─── FATS, NUTS & SEEDS ────────────────────────────────────────────────────
  {
    name: 'Peanut Butter (100% Natural, Creamy)',
    brand: 'Generic / Smuckers',
    servingSize: '2 tbsp (32g)',
    calories: 190,
    protein: 8.0,
    carbs: 7.0,
    fat: 16.0,
    barcode: '8410000000025',
    verified: true,
  },
  {
    name: 'Almonds (Raw/Dry Roasted)',
    brand: 'Generic',
    servingSize: '30g (~23 almonds)',
    calories: 174,
    protein: 6.3,
    carbs: 6.1,
    fat: 15.0,
    barcode: '8410000000026',
    verified: true,
  },
  {
    name: 'Extra Virgin Olive Oil',
    brand: 'Generic',
    servingSize: '1 tbsp (15ml / 14g)',
    calories: 119,
    protein: 0.0,
    carbs: 0.0,
    fat: 13.5,
    barcode: '8410000000027',
    verified: true,
  },
  {
    name: 'Avocado (Fresh, Raw)',
    brand: 'Generic Produce',
    servingSize: '100g (~1/2 medium avocado)',
    calories: 160,
    protein: 2.0,
    carbs: 8.5,
    fat: 14.7,
    barcode: '8410000000028',
    verified: true,
  },
  {
    name: 'Chia Seeds',
    brand: 'Generic',
    servingSize: '1 tbsp (12g)',
    calories: 58,
    protein: 2.0,
    carbs: 5.0,
    fat: 3.7,
    barcode: '8410000000029',
    verified: true,
  },

  // ─── FRUITS & VEGETABLES ───────────────────────────────────────────────────
  {
    name: 'Banana (Raw, Medium)',
    brand: 'Generic Produce',
    servingSize: '1 medium (118g)',
    calories: 105,
    protein: 1.3,
    carbs: 27.0,
    fat: 0.4,
    barcode: '8410000000030',
    verified: true,
  },
  {
    name: 'Apple (Raw, Gala/Fuji, Medium)',
    brand: 'Generic Produce',
    servingSize: '1 medium (182g)',
    calories: 95,
    protein: 0.5,
    carbs: 25.1,
    fat: 0.3,
    barcode: '8410000000031',
    verified: true,
  },
  {
    name: 'Blueberries (Fresh, Raw)',
    brand: 'Generic Produce',
    servingSize: '100g (1 cup)',
    calories: 57,
    protein: 0.7,
    carbs: 14.5,
    fat: 0.3,
    barcode: '8410000000032',
    verified: true,
  },
  {
    name: 'Broccoli (Steamed/Boiled)',
    brand: 'Generic Produce',
    servingSize: '100g',
    calories: 35,
    protein: 2.4,
    carbs: 7.2,
    fat: 0.4,
    barcode: '8410000000033',
    verified: true,
  },
  {
    name: 'Spinach (Fresh, Raw)',
    brand: 'Generic Produce',
    servingSize: '100g',
    calories: 23,
    protein: 2.9,
    carbs: 3.6,
    fat: 0.4,
    barcode: '8410000000034',
    verified: true,
  },

  // ─── POPULAR VIETNAMESE & ASIAN DISHES / STAPLES ───────────────────────────
  {
    name: 'Phở Bò (Beef Rice Noodle Soup - Lean Bowl)',
    brand: 'Traditional Vietnamese',
    servingSize: '1 medium bowl (~500ml broth + noodles + beef)',
    calories: 450,
    protein: 28.0,
    carbs: 58.0,
    fat: 11.0,
    barcode: '8410000000035',
    verified: true,
  },
  {
    name: 'Cơm Gà Xối Mỡ / Roasted Chicken Rice',
    brand: 'Traditional Vietnamese',
    servingSize: '1 portion (1 cup rice + 1 chicken leg)',
    calories: 620,
    protein: 34.0,
    carbs: 65.0,
    fat: 24.0,
    barcode: '8410000000036',
    verified: true,
  },
  {
    name: 'Bánh Mì Thịt Nướng (Grilled Pork Baguette)',
    brand: 'Traditional Vietnamese',
    servingSize: '1 sandwich (~180g)',
    calories: 410,
    protein: 19.0,
    carbs: 48.0,
    fat: 15.0,
    barcode: '8410000000037',
    verified: true,
  },
  {
    name: 'Gỏi Cuốn (Shrimp & Pork Summer Rolls)',
    brand: 'Traditional Vietnamese',
    servingSize: '2 rolls (with peanut sauce)',
    calories: 170,
    protein: 9.5,
    carbs: 24.0,
    fat: 4.0,
    barcode: '8410000000038',
    verified: true,
  },
  {
    name: 'Cơm Tấm Sườn Bì Chả (Broken Rice w/ Pork Chop)',
    brand: 'Traditional Vietnamese',
    servingSize: '1 standard plate',
    calories: 680,
    protein: 36.0,
    carbs: 72.0,
    fat: 27.0,
    barcode: '8410000000039',
    verified: true,
  },
  {
    name: 'Khoai Lang Luộc (Boiled Vietnamese Sweet Potato)',
    brand: 'Traditional Vietnamese',
    servingSize: '100g',
    calories: 86,
    protein: 1.6,
    carbs: 20.1,
    fat: 0.1,
    barcode: '8410000000040',
    verified: true,
  },
  {
    name: 'Sữa Đậu Nành (Unsweetened Soy Milk)',
    brand: 'Generic / Vinasoy',
    servingSize: '1 glass (250ml)',
    calories: 80,
    protein: 7.0,
    carbs: 4.0,
    fat: 4.0,
    barcode: '8934567890123',
    verified: true,
  },
];

async function main() {
  console.log('🥗 Seeding initial FoodItem database...');
  let added = 0;
  for (const item of foods) {
    await prisma.foodItem.upsert({
      where: { barcode: item.barcode },
      update: {
        name: item.name,
        brand: item.brand,
        servingSize: item.servingSize,
        calories: item.calories,
        protein: item.protein,
        carbs: item.carbs,
        fat: item.fat,
        verified: item.verified,
      },
      create: item,
    });
    added++;
  }
  console.log(`✅ Successfully seeded/updated ${added} food items!`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
    await pool.end();
  });
